### ISSUE TITLE
Better validate subuids

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#164]
Here is the case. 

```
user@host:~/Documents/src/vaggatest$ cat /etc/subuid 
# empty default subuid/subgid file
user:0:65535

user@host:~/Documents/src/vaggatest$ vagga py3
thread '<main>' panicked at 'assertion failed: uid == rng.start()', src/container/uidmap.rs:156
```
1. Zero must not be used as a start range.
2. Anything < 65536 should produce a warning

**Comment by tailhook** [comment]
Another thing that should be check for is:
```

thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:326
stack backtrace:
   1:           0xb8d230 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:           0xb9030b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:           0xb8ff93 - std::panicking::default_hook::haac48fa641db8fa2
   4:           0xb7b5af - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:           0xb7cfd8 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:           0xb8c711 - rust_begin_unwind
   7:           0xbdb6ef - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:           0xbdb9c8 - core::panicking::panic::hdbcf9a6d5c170498
   9:           0x589412 - _<std..option..Option<T>>::unwrap::hb7d9828810478b76
                        at ../src/libcore/macros.rs:21
  10:           0x588a78 - vagga::container::uidmap::match_ranges::h4506a9edc578fef5
                        at src/container/uidmap.rs:63
  11:           0x5a2857 - vagga::container::uidmap::map_users::_$u7b$$u7b$closure$u7d$$u7d$::h5319c4918edf06fc
                        at src/container/uidmap.rs:223
  12:           0x5a255c - vagga::container::uidmap::make_uidmap::h689cd03fa2b3b61f
                        at src/container/uidmap.rs:141
  13:           0x5a0d0d - vagga::container::uidmap::map_users::hc2fa338f9701680b
                        at src/container/uidmap.rs:222
  14:           0x5f8693 - _<unshare..Command as launcher..wrap..Wrapper>::map_users_for::hca65593a8badd152
                        at src/launcher/wrap.rs:79
  15:           0x5fd14e - vagga::launcher::build::build_internal::h255ba2f8f780b75d
                        at src/launcher/build.rs:89
  16:           0x5f6d57 - vagga::launcher::build::build_container::h445d7a3f8e2c4708
                        at src/launcher/build.rs:19
  17:           0x5ed3c4 - vagga::launcher::simple::prepare_containers::h7b56206fbaac229e
                        at src/launcher/simple.rs:61
  18:           0x5e6585 - vagga::launcher::user::run_commands::hbcea7d10c4622895
                        at src/launcher/user.rs:86
  19:           0x5e3863 - vagga::launcher::user::run_user_command::h8e4984063bcac1d9
                        at src/launcher/user.rs:26
  20:           0x5ccb41 - vagga::launcher::run::h325058be5394cec6
                        at src/launcher/mod.rs:253
  21:           0x402b4c - vagga::launcher::main::hddab9b77655c3fb4
                        at src/launcher/mod.rs:269
  22:           0x401deb - vagga::main::h6fd685eb63b02a3e
                        at src/main.rs:70
  23:           0xb8fbd4 - std::sys_common::unwind::try::try_fn::h09ba69fd13531e58
  24:           0xb8c69b - __rust_try
  25:           0xb8f7db - std::rt::lang_start::h5b0863080165c75e
  26:           0x403479 - main
```

**Comment by tailhook** [comment]
And another error when user is in subuid and not in subgid:
```
> RUST_BACKTRACE=1 vagga run
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
stack backtrace:
   1:           0xd1b99f - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:           0xd200bd - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:           0xd1efaa - std::panicking::default_hook::h0ac3811ec7cee78c
   4:           0xd1f548 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:           0xd1f3e2 - std::panicking::begin_panic::h6ed03353807cf54d
   6:           0xd1f320 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   7:           0xd1f2a1 - rust_begin_unwind
   8:           0xd7e39f - core::panicking::panic_fmt::h27224b181f9f037f
   9:           0xd7e2cb - core::panicking::panic::h53676c30b3bd95eb
  10:           0x4e1a56 - <core::option::Option<T>>::unwrap::hb9a3a927f86ae450
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/obj/../src/libcore/macros.rs:21                                                                
  11:           0x786a88 - vagga::container::uidmap::match_ranges::hacc01215b96be02c                                                                                                         
                        at /work/src/container/uidmap.rs:63                                                                                                                                  
  12:           0x93b878 - vagga::container::uidmap::map_users::{{closure}}::h02488d9bddd325f7                                                                                               
                        at /work/src/container/uidmap.rs:229                                                                                                                                 
  13:           0x787cd6 - vagga::container::uidmap::make_uidmap::hd2ed1d92b55456d3                                                                                                          
                        at /work/src/container/uidmap.rs:139                                                                                                                                 
  14:           0x78c259 - vagga::container::uidmap::map_users::hd8aef315354bdaaa                                                                                                            
                        at /work/src/container/uidmap.rs:220                                                                                                                                 
  15:           0x7c2cf2 - <unshare::Command as vagga::launcher::wrap::Wrapper>::map_users_for::h81a6ee67497e4040                                                                            
                        at /work/src/launcher/wrap.rs:82
  16:           0x7ae293 - vagga::launcher::build::build_internal::h62f97b807fd898a6
                        at /work/src/launcher/build.rs:93
  17:           0x7abe2d - vagga::launcher::build::build_container::h931bff92e01a70ce
                        at /work/src/launcher/build.rs:19
  18:           0x7b855f - vagga::launcher::supervisor::prepare_containers::ha3bd6766a6ff2a8b
                        at /work/src/launcher/supervisor.rs:142
  19:           0x7a7fa1 - vagga::launcher::user::run_commands::h5cef95654d3e041c
                        at /work/src/launcher/user.rs:91```
