### ISSUE TITLE
`vagga doc` failing with missing sphinx dependency

### ISSUE THREAD

**Issue by livioribeiro** [tailhook/vagga#294]
Building documentation fails with the following message:

```
sphinx-build -b html -d _build/doctrees   . _build/html
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'imagesize' distribution was not found and is required by Sphinx
Makefile:53: recipe for target 'html' failed
make: *** [html] Error 1
```

This is happening because the package [py-sphinx](http://pkgs.alpinelinux.org/package/v3.4/main/x86_64/py-sphinx) (version 1.4.1-r0) currently does not have [py-imagesize](http://pkgs.alpinelinux.org/package/edge/main/x86_64/py-imagesize) as a dependency since `py-imagesize` is still in the branch `edge` of the alpine repository.

A simple solution would be adding the missing `imagesize` dependency using pip:

```yaml
containers:
  docs:
    setup:
    - !Alpine v3.4
    - !Install [alpine-base, py-sphinx, make]
    - !Py2Install [imagesize] # add the missing dependency
    - !Py2Requirements docs/requirements.txt
```

**Comment by anti-social** [comment]
Fixed https://github.com/tailhook/vagga/pull/292
